export const locations = [
    { name: "banteay meanchey" },
    { name: "battambang" },
    { name: "kampong cham" },
    { name: "kampong chhang" },
    { name: "kampong speu" },
    { name: "kampong thom" },
    { name: "kampot" },
    { name: "kandal" },
    { name: "Kep" },
    { name: "koh kong" },
    { name: "kratié" },
    { name: "mondulkiri" },
    { name: "Oddar Meanchey" },
    { name: "pailin" },
    { name: "Phnom Penh" },
    { name: "Preah Sihanouk" },
    { name: "preah Vihear" },
    { name: "prey Veng" },
    { name: "pursat" },
    { name: "Siem Reap" },
    { name: "stung treng" },
    { name: "svay rieng" },
    { name: "takéo" },
    { name: "tboung khmum" },
]
