export {default as Facebook} from "./Facebook";
export {default as FacebookF} from "./FacebookF"
export {default as TwitterX} from "./TwitterX"
export {default as Instagram} from "./Instagram"
export {default as Google} from "./Google"
export {default as Star} from "./Star"
export {default as StarFill } from "./StarFill"
export {default as Map} from "./Map"
export {default as Menul} from "./Menu"
export {default as IconSearch} from "./Search"
export {default as IconLocation} from "./Location"
export {default as IconBedRoom} from "./BedRoom"
