export const categories = [
    { name: "Apartment" },
    { name: "Villa" },
    { name: "House" },
    { name: "Condo" },
    { name: "Townhouse" },
    { name: "Penthouse" },
    { name: "Duplex" },
    { name: "Studio" },
    { name: "Commercial Property" },
    { name: "Shop/Office Space" },
    { name: "Land" },
    { name: "Residential" },
    { name: "Commercial" },
    { name: "Industrial" },
    { name: "Agricultural" },
    { name: "Mixed-use" },
    { name: "Vacation Home" },
    { name: "Rental Properties" },
    { name: "Fixer-upper" },
    { name: "Luxury Properties" },
    { name: "Foreclosed Properties" },
    { name: "New Developments" },
    { name: "Off-plan Properties" },
  ];