name: CI/CD Pipeline for API Gateway Service

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/backend/auth-service/**"
  push:
    branches:
      - main
    paths:
      - "apps/backend/auth-service/**"

defaults:
  run:
    working-directory: apps/backend/auth-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all branches and tags are fetched

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the version of Node.js that your project requires

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Run build
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./apps/backend/auth-service/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./apps/backend/auth-service/build

      - name: Prepare Deployment Directories
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/ubuntu/apps/auth-service/build
            mkdir -p /home/ubuntu/apps/auth-service/build/configs

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./apps/backend/auth-service/build/*"
          target: "/home/ubuntu/apps/auth-service/build"
          strip_components: 4
      
      - name: Create .env File
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
         
            echo "PORT=${{ secrets.AUTH_SERVICE_PORT }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "COGNITO_APP_CIENTID=${{ secrets.COGNITO_APP_CIENTID }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "COGNITO_APP_CIENTSECRET=${{ secrets.COGNITO_APP_CIENTSECRET }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "AWSREGION=${{ secrets.AWSREGION }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "USER_POOL_ID=${{ secrets.USER_POOL_ID }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "COGNITO_APP_DOMAIN=${{ secrets.COGNITO_APP_DOMAIN }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "REDIRECT_TO_FRONTEND=${{ secrets.REDIRECT_TO_FRONTEND }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
            echo "USER_SERVICE_DOMAIN=${{ secrets.USER_SERVICE_DOMAIN }}" >> /home/ubuntu/apps/auth-service/build/configs/.env.production
          
      - name: Install Dependencies and Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Load the full user environment for non-interactive shells
            source /home/ubuntu/.nvm/nvm.sh
            source /home/ubuntu/.profile

            cd /home/ubuntu/apps/auth-service/build
            yarn install --production

            # Check if the PM2 process is running
            if pm2 show auth-service > /dev/null; then
              echo "Application is running. Restarting..."
              yarn restart
            else
              echo "Application is not running. Starting..."
              yarn start:pm2-production
            fi
